-- OAuth tokens, per connection.
--
-- Deliberately NOT in builder_secrets, and that is the interesting decision.
--
-- The vault is built around an agent asking to reveal a secret an operator
-- granted it — a model that assumes a human placed the value there once and
-- several principals read it later. An OAuth token is the opposite shape: the
-- provider issues it TO one connection, it expires on its own schedule, it is
-- replaced silently by a refresh, and nobody else ever reads it. Forcing it
-- through the grants table would mean inventing a principal per connection,
-- which is precisely the foreign-key impossibility SF-001 describes.
--
-- So this table is the storage, and the consequence is worth stating plainly:
-- OAuth integrations are NOT blocked by SF-001. Google Analytics, Search
-- Console and anything else that can do the redirect dance can work today.
--
-- The refresh token is the sensitive one — an access token expires in an hour,
-- a refresh token is a standing grant until revoked. Both are stored encrypted
-- at rest by the same envelope the vault uses; this table holds ciphertext.

BEGIN;

CREATE TABLE IF NOT EXISTS builder_oauth_tokens (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Which integration this belongs to (slug from internal/integrations), and
    -- which configured connection, when there is more than one of a kind.
    integration   text NOT NULL,
    connection_id uuid REFERENCES builder_sources(id) ON DELETE CASCADE,

    -- The provider's own account identity, so the UI can say WHOSE account is
    -- connected. Without it "Connected" is unfalsifiable — you cannot tell you
    -- authorised the wrong Google account until the data looks wrong.
    account       text NOT NULL DEFAULT '',

    access_token  bytea NOT NULL,
    refresh_token bytea,
    -- Space-separated, as the provider returned them. Stored rather than
    -- assumed: a provider may grant FEWER scopes than were asked for, and code
    -- that assumes it got what it requested fails later and elsewhere.
    scopes        text NOT NULL DEFAULT '',
    token_type    text NOT NULL DEFAULT 'Bearer',
    expires_at    timestamptz,

    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- One live token per integration+connection. A second authorization replaces
-- the first rather than accumulating, so "which token is current?" has one
-- answer.
CREATE UNIQUE INDEX IF NOT EXISTS builder_oauth_tokens_uniq
    ON builder_oauth_tokens (integration, COALESCE(connection_id, '00000000-0000-0000-0000-000000000000'::uuid));

-- The refresh sweep asks "what expires soon?".
CREATE INDEX IF NOT EXISTS builder_oauth_tokens_expiry_idx
    ON builder_oauth_tokens (expires_at)
    WHERE refresh_token IS NOT NULL;

-- In-flight authorization attempts.
--
-- The `state` parameter is the CSRF defence for the whole flow: without it, an
-- attacker can hand a victim a callback URL carrying the attacker's own code
-- and bind the attacker's account to the victim's connection. It has to be
-- generated by us, single-use, and short-lived — which means it needs a row.
CREATE TABLE IF NOT EXISTS builder_oauth_states (
    state         text PRIMARY KEY,
    integration   text NOT NULL,
    connection_id uuid,
    -- PKCE verifier. Sent as a challenge on the authorize leg and echoed here
    -- on exchange, so an intercepted code is useless without it.
    verifier      text NOT NULL DEFAULT '',
    redirect_uri  text NOT NULL DEFAULT '',
    created_by    text NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL DEFAULT now(),
    -- Short. An authorization a human abandoned should not stay usable.
    expires_at    timestamptz NOT NULL DEFAULT now() + interval '15 minutes'
);

CREATE INDEX IF NOT EXISTS builder_oauth_states_expiry_idx
    ON builder_oauth_states (expires_at);

COMMENT ON TABLE builder_oauth_tokens IS
  'OAuth tokens per connection. Separate from builder_secrets because a provider-issued, self-refreshing token is a different shape from a human-placed secret — see SF-001.';

COMMIT;
